name: Deploy to S3 and Invalidate CloudFront

on: 
  push:
    branches: 
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: github Repository 파일불러오기
        uses: actions/checkout@v4
    
      - name: 의존성 설치 
        run: npm i 

      - name: 빌드하기 
        run: npm run build  
      
      - name: Aws Resource 에 접근할 수 있게 AWS 인증 설정  
        uses: aws-actions/configure-aws-credentials@v4  # Aws-actions → aws-actions
        with: 
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # 오타 수정
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # 오타 수정

      - name: s3 기존 파일을 전체 삭제 
        run: aws s3 rm --recursive s3://instgamr

      - name: s3에 빌드된 파일 업로드 하기
        run: aws s3 cp ./dist s3://instgamr --recursive  
