name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 저장소 파일 불러오기
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. 의존성 설치
      - name: Install Dependencies
        run: npm install

      # 3. 빌드 실행
      - name: Build Project
        run: npm run build

      # 4. AWS 인증 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 5. 기존 S3 파일 전체 삭제
      - name: Delete Existing S3 Files
        run: |
          aws s3 rm --recursive s3://instgamr
